server:
  port: 8084
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coursedatabase
    username: root
    password: aswal
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
    
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
   
    
    
  